### ISSUE TITLE
Add K and M values as optional values to storageCluster yaml config

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#268]
Currently the `k`+`m` values are global. However it would be great if those values could also be customized per vdisk, which would result in a (`tlogserver`) config such as:

```yaml
storageClusters:
  tlogcluster:
    dataStorage: # k+m server configs
    - address: 192.168.122.76:2000
    - address: 192.168.122.76:2001
    - address: 192.168.122.76:2002
    - address: 192.168.122.76:2003
    tlog:
      k: 2
      m: 2
vdisks:
  myvdisk:
    tlogStorageCluster: tlogcluster
    k: 2 # optional, if not given the global k value is used
    m: 2 # optional, if not given the global m value is used
```

This feature would obviously only work, if we use the config-based redis pool factory (which is selected only when the `-memorystorage` and `-storage-addresses` flags are NOT specified).

Also I think it would make sense, if we make sure that we validate that if either `k` or `m` is given for a vdisk, that the other value of the pair `k+m` is also given, as it would be super confusing to allow one to be local and the other to be global.

**Comment by robvanmieghem** [comment]
@GlenDC I think these should be marked per storagecluster since the storagecluster deployment strategy would define the k and m values.

**Comment by GlenDC** [comment]
But the storage cluster doesn't know it's a tlog storage cluster, and either way we can validate it in both cases. But yeah I guess we can add it to the storage cluster if that's what is wanted.

The orchestrator chat seemed to indicate it should be a per vdisk thing though? Or did I miss something?

**Comment by iwanbk** [comment]
How about removing the `K` & `M` config?
```yaml
dataStorage: # 3 servers -> k = 3
    - address: 192.168.122.76:2000
    - address: 192.168.122.76:2001
    - address: 192.168.122.76:2002
paritystorage: # 1 storage -> M = 1 
    - address: 192.168.122.76:2003
```

**Comment by robvanmieghem** [comment]
> The orchestrator chat seemed to indicate it should be a per vdisk thing though? Or did I miss something?

Was more a discussion/question but the components having info about the vdisks are different than the ones controlling the storageclusterconfiguration and rollout.

**Comment by robvanmieghem** [comment]
@iwanbk which is basically the same but more verbose.

**Comment by GlenDC** [comment]
Should we go for @iwanbk's proposal than, @robvanmieghem?

**Comment by robvanmieghem** [comment]
I would just put the properties k & m on the storagecluster

**Comment by GlenDC** [comment]
Ok fair enough.

**Comment by GlenDC** [comment]
@zaibon you have more overview than me on how 0-Disk is used within the ecosystem. If this feature is still required, and the description as formed in this issue makes you happy, than feel free to move it to milestone 6 and we can assign it to @chrisvdg.

**Comment by iwanbk** [comment]
we need this for #230, and not optional but mandatory.
I have no strong opinion about the config format, but still vote for my own proposal https://github.com/zero-os/0-Disk/issues/268#issuecomment-308461641

**Comment by GlenDC** [comment]
Implementing this is not the issue, can be done super fast. But this has to be first coordinated with people like @FastGeert and @rkhamis (or whoever from 0-Orchestrator needs to be involved in this design), so we're all on the same page on this.

**Comment by GlenDC** [comment]
@FastGeert and @zaibon can we have a quick zoom meeting about this tomorrow?

**Comment by GlenDC** [comment]
@iwanbk while I like your proposal, it doesn't map to how 0-stor works. I went through that part of the 0-Stor codebase, and it seems to select random servers. In your proposal the config explicitly defines which servers are data-shards, and which are used as parity shards. This is very user-friendly, as the user can basically never define `k` and `m` values that do not make any sense. However it would be very non-userfriendly due to the fact that we would be faking this mapping, as it would not be respected at all, as far as I can see.

So therefore I'll go for the following config instead:

```yaml
iyo: #all iyo fields are required
  org: "foo org" # iyo organisation
  namespace: "foo namespace" #iyo namespace 
  clientID: "foo client" #iyo client id
  secret: "foo secret" #iyo secret
metadataServers: # required, at least 1 server is required
  - address: "3.3.3.3:33" # has to be valid dial string
dataServers: # dataShards+parityShards server required
  - address: "1.1.1.1:11" # has to be valid dial string
  - address: "2.2.2.2:22"
  - address: "2.2.2.2:33"
  - address: "2.2.2.2:44"
  - address: "2.2.2.2:55"
  - address: "2.2.2.2:66"
dataShards: 4
parityShards: 2
```
