### ISSUE TITLE
vdisk restore fails but returns success

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-Disk#288]
We use qemu for core0's VM creations mainly because it has out of the box nbd protocol support.

**For starting core0 VM:**
- We first start tlogserver: `/bin/tlogserver  -address 192.168.58.79:11211  -k 1  -m 1  -config /tlog_vm0.config`
```
storageClusters:
  mytlog:
    dataStorage:
    - address: 192.168.122.76:2002
    - address: 192.168.122.79:2002
vdisks:
  vd2:
    tlogStorageCluster: mytlog
```
- then starting nbdserver and passing tlogrpc address `/bin/nbdserver -protocol unix  -address "/server.socket.vm0"  -tlogrpc 192.168.58.79:11211 -config /nbd_vm0.config`

```
storageClusters:
  -4878563674217233462:
    dataStorage:
    - address: 192.168.20.132:16379
    metadataStorage:
      address: 192.168.20.132:16379
  mytlog:
    dataStorage:
    - address: 192.168.122.76:2002
    - address: 192.168.122.79:2002
    label: mytlog
    metadataStorage:
      address: 192.168.122.79:2003
    nodes:
    - '525400123456'
    - '525400123459'
    status: ready
  mycluster:
    dataStorage:
    - address: 192.168.122.76:2000
    - address: 192.168.122.79:2000
    label: mycluster
    metadataStorage:
      address: 192.168.122.79:2001
    nodes:
    - '525400123456'
    - '525400123459'
    status: ready
vdisks:
  vd2:
    blockSize: 4096
    id: vd2
    readOnly: false
    rootStorageCluster: -4878563674217233462
    size: 4
    storageCluster: mycluster
    tlogstoragecluster: mytlog
    type: boot
```

**For stopping core0 VM:**
- First we destroy the vm using `kvm.destroy`, which I here assume `qemu` will detach the vdisk and nbd
- We stop the nbd server by sending a `SIGTERM`
- after the nbd server is stopped we do the same for the `tlogserver`

**For vdisk rollback**
- We rollback using zeroctl: `/bin/zeroctl restore vdisk vd2 --config /config.yaml --end-ti
mestamp 1498112005000000000 --k 1 --m 1`
```  mycluster:                                                                                                                                                                                                         
    dataStorage:                                                                                                                                                                                                     
    - address: 192.168.122.79:2000                                                                                                                                                                                   
    - address: 192.168.122.76:2000                                                                                                                                                                                   
    label: mycluster                                                                                                                                                                                                 
    metadataStorage:                                                                                                                                                                                                 
      address: 192.168.122.76:2001                                                                                                                                                                                   
    nodes:                                                                                                                                                                                                           
    - '525400123459'                                                                                                                                                                                                 
    - '525400123456'                                                                                                                                                                                                 
    status: ready                                                                                                                                                                                                    
  mytlog:                                                                                                                                                                                                            
    dataStorage:                                                                                                                                                                                                     
    - address: 192.168.122.79:2002                                                                                                                                                                                   
    - address: 192.168.122.76:2002                                                                                                                                                                                   
    label: mytlog                                                                                                                                                                                                    
    metadataStorage:                                                                                                                                                                                                 
      address: 192.168.122.76:2003                                                                                                                                                                                   
    nodes:                                                                                                                                                                                                           
    - '525400123459'                                                                                                                                                                                                 
    - '525400123456'                                                                                                                                                                                                 
    status: ready                                                                                                                                                                                                    
vdisks:                                                                                                                                                                                                              
  vd2:
    blockSize: 4096
    readOnly: false
    size: 4
    storageCluster: mycluster
    tlogStorageCluster: mytlog
    type: boot
```
