### ISSUE TITLE
Nbd server failed to read template data

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-Disk#364]
* I have the below storage cluster configured
**`mycluster:cluster:conf:storage`**
```yaml
dataStorage:
- address: 192.168.122.79:2000
- address: 192.168.122.76:2000
label: mycluster
metadataStorage:
  address: 192.168.122.76:2001
nodes:
- '525400123459'
- '525400123456'
status: ready
```

* Template cluster configured
**`-8207316437363886335:cluster:conf:storage`**
```yaml
dataStorage:
- address: 192.168.20.132:16379
metadataStorage:
  address: 192.168.20.132:16379
```

* template configured like below. Note: I tried with and without `templateVdiskID`
**`template:ubuntu-1604:vdisk:conf:static`**
```yaml
blockSize: 4096
readOnly: false
size: 4
templateVdiskID: template:ubuntu-1604
type: boot
```

* nbd for template configured like below. Note: I tried to point the `storageClusterID` to `mycluster` and have the `templateStrogaeClusterID` to `8207316437363886335` but zeroctl could not find the template key and it worked when I modified like below
**`template:ubuntu-1604:vdisk:conf:storage:nbd`**
```yaml
storageClusterID: '-8207316437363886335'
```
* After that I ran the following `./bin/zeroctl copy vdisk --config {etcdip} template:ubuntu-1604 vd2 mycluster`, after a few checks looks like the metadata was copies successfully.

* After that I saved the following config to etcd. Note: again I tried with and without `templateVdiskID`
**`vd2:vdisk:conf:static`**
```yaml
blockSize: 4096
readOnly: false
size: 4
templateVdiskID: template:ubuntu-1604
type: boot
```

* vd2 nbd config
**`vd2:vdisk:conf:storage:nbd`**
```yaml
storageClusterID: mycluster
templateStorageCluster: '-8207316437363886335'
```

* then finally I save vm1 config
**`vm1:nbdserver:conf:vdisks`**
```yaml
vdisks:
- vd2
```

* And I run the ` /bin/nbdserver             -protocol unix             -address "
/server.socket.vm1"             -id "vm1"             -config "192.168.122.76:2379"`

* Nbd server starts and from the logs it has no problem, but actually the data of the template is not there. So metadata was copied successfully (I believe) but the data had an issue

**Comment by GlenDC** [comment]
> templateVdiskID

This property is only required when you have a nondeduped vdisk _AND_ the ID of the template disk is different than the (target) vdisk you are adding template support for. Because with deduped vdisks (e.g. a boot vdisk) we only care about the data, and to access that all we need is their blake2 hash, so that's definitely not going to help you.

---

Will check out the rest of your issue and apply it locally here to track down the issue, thank you for reporting!

**Comment by GlenDC** [comment]
So based on your issue description I try to reproduce it as follows.

1. Use config "equal" to the one described in issue:

```yaml
storageClusters:
  mycluster:
    dataStorage:
      - address: localhost:16379
      - address: localhost:16380
    metadataStorage:
      address: localhost:16381
  8207316437363886335:
    dataStorage:
      - address: localhost:16382
    metadataStorage:
      address: localhost:16382
vdisks:
  vd2:
    type: boot
    blockSize: 4096
    size: 4
    nbd:
      storageClusterID: mycluster
      templateStorageClusterID: 8207316437363886335
  template:ubuntu-1604:
    type: boot
    blockSize: 4096
    size: 4
    nbd:
      storageClusterID: 8207316437363886335
```

2. Start the `nbdserver`:

```
$ nbdserver -protocol tcp -address localhost:6666 -id vm2 -v
```

3. Create `template:ubuntu-1604` vdisk:

```
$ qemu-img convert -p -n ubuntu-16.04-server-cloudimg-amd64-disk1.img \
    -O nbd nbd+tcp://localhost:6666/template:ubuntu-1604
```

4. Copy metadata to target vdisk:

```
$ zeroctl copy vdisk template:ubuntu-1604 vd2 mycluster -v
```

5. Mount `vd2` vdisk:

```
$  qemu-system-x86_64 -machine pc-1.3,usb=off -boot order=c -m 2048 -smp 2 \
    -net nic -net user -drive file=nbd+tcp://localhost:6666/vd2,index=0,format=raw
```

Result: `vd2` boots up just fine, running `Ubuntu 16.04.2 LTS`.

---

Of course you use the ETCD-based configuration, so I made a quick tool to transfer a developer yaml file config directly to an ETCD cluster, as to help with testing using the ETCD-based configuration now and in the future. Even though it shouldn't really matter as almost all configuration logic is the same, no matter if you choose file- or ETCD-based configuration.

Anyhow, you can find the tool under [`/tools/import_file_into_etcd_config.go`](https://github.com/zero-os/0-Disk/tree/master/tools/import_file_into_etcd_config) , should you ever need it, which I guess you don't, but mentioning it here for completeness.

So using that tool I get:

```
$ ./import_file_into_etcd_config -id vm2 127.0.0.1:2379
```

written config to 'mycluster:cluster:conf:storage':
```yaml
dataStorage:
- address: localhost:16379
  db: 0
- address: localhost:16380
  db: 0
metadataStorage:
  address: localhost:16381
  db: 0
```

written config to '8207316437363886335:cluster:conf:storage':
```yaml
dataStorage:
- address: localhost:16382
  db: 0
metadataStorage:
  address: localhost:16382
  db: 0
```

written config to 'vd2:vdisk:conf:static':
```yaml
blockSize: 4096
readOnly: false
size: 4
type: boot
templateVdiskID: ""
```

written config to 'vd2:vdisk:conf:storage:nbd':
```yaml
storageClusterID: mycluster
templateStorageClusterID: "8207316437363886335"
slaveStorageClusterID: ""
tlogServerClusterID: ""
```

written config to 'template:ubuntu-1604:vdisk:conf:static':
```yaml
blockSize: 4096
readOnly: false
size: 4
type: boot
templateVdiskID: ""
```

written config to 'template:ubuntu-1604:vdisk:conf:storage:nbd':
```yaml
storageClusterID: "8207316437363886335"
templateStorageClusterID: ""
slaveStorageClusterID: ""
tlogServerClusterID: ""
```

written config to 'vm2:nbdserver:conf:vdisks':
```yaml
vdisks:
- vd2
- template:ubuntu-1604
```

With that config ready, I start from a clean state, and execute the following steps once again:

1. Start the `nbdserver`:

```
$ nbdserver -protocol tcp -address localhost:6666 -config 127.0.0.1:2379 -id vm2 -v
```

2. Create `template:ubuntu-1604` vdisk:

```
$ qemu-img convert -p -n ubuntu-16.04-server-cloudimg-amd64-disk1.img \
    -O nbd nbd+tcp://localhost:6666/template:ubuntu-1604
```

3. Copy metadata to target vdisk:

```
$ zeroctl copy vdisk template:ubuntu-1604 vd2 mycluster --config 127.0.0.1:2379 -v
```

4. Mount `vd2` vdisk:

```
$  qemu-system-x86_64 -machine pc-1.3,usb=off -boot order=c -m 2048 -smp 2 \
    -net nic -net user -drive file=nbd+tcp://localhost:6666/vd2,index=0,format=raw
```

Result: `vd2` boots up just fine, running `Ubuntu 16.04.2 LTS`.

_NOTE_: that you'll see that I do have `template:ubuntu-1604` listed in `vm2:nbdserver:conf:vdisks`.
This isn't a requirement, and in fact it should work just fine without doing so, I just have it because
my tool automatically adds all found vdisks to the config.

While all your functionality should work when not listing the vdisks in the `NBDVdisksConfig`,
it does mean that you won't have pre-validation of the configs used only by the template vdisk `template:ubuntu-1604`.

Again, that shouldn't be an issue, as the `zerodisk copy vdisk` should fail in case
you would have an issue due to a bad configuration.

Even though I knew for sure that this shouldn't cause the issue you're describing,
for the sake of completeness I did a semi-clean-state test where I just do step 3 and 4,
and it works as well. So that's defintely not the issue.

--- 

So with that done I'm not entirely sure why it didn't work for you @khaledkbadr.

Could you run the `zerodisk copy vdisk` command with the `verbose` flag (`-v`), might perhaps give some more insight, even though I would be surprised it didn't work in case it returned a statuc code of `0`.

---

> Note: I tried to point the `storageClusterID` to `mycluster` and have the `templateStrogaeClusterID` to
> `8207316437363886335` but zeroctl could not find the template key and it worked when I modified like below
> **`template:ubuntu-1604:vdisk:conf:storage:nbd`**
> ```yaml
> storageClusterID: '-8207316437363886335'
> ```

That's weird, in my tests I didn't encounter this issue. Again, giving the verbose output of the copy command might tell us more. But what your describing is new to me.

---

Also please attach logs to issues you create whenever possible,
as it might be able to help us identify the issue you're facing.
