### ISSUE TITLE
VM doesn't boot correctly after restoring its boot disk

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-Disk#425]
**Steps to reproduce**:
* Copy vdisk from a template (vd2)
* Start a VM using qemu with nbd, tlog servers
* echo a file for in the VM after it boots
* Stop the VM (and stopping nbd, tlog servers)
* restore the vdisk `/bin/zeroctl restore vdisk -f vd2 --config 192.168.122.79:2379 --end-timestamp 1504018830000000000 --data-shards 1 -v --parity-shards 1`
* Start the vm again with nbd, tlog servers, it halts at this 
![image](https://user-images.githubusercontent.com/6059889/29828478-79159468-8ce5-11e7-859f-9a77f58a5a59.png)

**config in etcd**
```
vd2:vdisk:conf:static
blockSize: 4096
readOnly: false
size: 4
type: boot

vd2:vdisk:conf:storage:nbd
slaveStorageClusterID: ''
storageClusterID: myblockcluster
templateStorageClusterID: 87ec688e821f5f0006619b7207d656bd
tlogServerClusterID: tlogserver_vm0_525400123456

vd2:vdisk:conf:storage:tlog
zeroStorClusterID: myobjectcluster


myblockcluster:cluster:conf:storage
dataStorage:
- address: 192.168.122.76:2000
- address: 192.168.122.79:2000
label: myblockcluster
metadataStorage:
  address: 192.168.122.79:2001
nodes:
- '525400123456'
- '525400123459'
status: ready

myobjectcluster:cluster:conf:zerostor
iyo:
  clientID: <clientID>
  namespace: test
  org: zero-khaled
  secret: <secret>
metadataServers:
- address: 192.168.122.79:2379
servers:
- address: 192.168.122.76:2002
- address: 192.168.122.79:2002

vm0:nbdserver:conf:vdisks
vdisks:
- vd2

tlogserver_vm0_525400123456:cluster:conf:tlog
servers:
- 192.168.122.79:11211
```
