### ISSUE TITLE
expand the existing vdisk data shard index algorithm

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#443]
The current algorithm used to compute the data shard index for a vdisk does not take into account that one or multiple shards in a cluster can be offline.

A new algorithm has been designed as part of #438:

```go
func (s *storage) getShardIndex(blockIndex int64) int64 {
	// first try the modulo sharding,
	// which will work for all default online shards
	// and thus keep it as cheap as possible
	si := blockIndex % s.shardCount
	var offline bool
	if _, offline = s.offlineShards[si]; !offline {
		return si
	}

	// keep trying until we find a non-offline shard
	// in the same reproducable manner
	// (another kind of tracing)
	for {
		si = int64(jumpConsistentHash(uint64(blockIndex), int32(s.shardCount)))
		if _, offline = s.offlineShards[si]; !offline {
			return si
		}
		blockIndex++
	}
}

// jumpConsistentHash taken from https://arxiv.org/pdf/1406.2294.pdf
func jumpConsistentHash(key uint64, numBuckets int32) int32 {
	var b int64 = -1
	var j int64

	for j < int64(numBuckets) {
		b = j
		key = key*2862933555777941757 + 1
		j = int64(float64(b+1) * (float64(int64(1)<<31) / float64((key>>33)+1)))
	}

	return int32(b)
}
```

A playground example has also been created to see the algorithm at work: https://play.golang.org/p/2n-fIvbIfa

Besides integrating this algorithm we also want to support a new property for data shards, such that upper layers can explicitly disable a shard, while still keeping it defined. Such a property would look like:

```yaml
dataStorage:
    - address: localhost:16380
      disabled: true
    - address: localhost:16380
      db: 1
    - address: localhost:16382
      disabled: false
metadataStorage:
    address: localhost:16379
```

Note that when the `disabled` property is given for a shard, it doesn't make sense that we would still validate or even require the address property to be given, so an equally valid (storage cluster) config would be:

```yaml
dataStorage:
    - disabled: true
    - address: localhost:16380
      db: 1
    - address: localhost:16382
metadataStorage:
    address: localhost:16379
```
