### ISSUE TITLE
error trying to use object cluster and block cluster in zeroctl copy 

### ISSUE THREAD

**Issue by abdulrahmantkhalifa** [zero-os/0-Disk#490]
## setup 
-  three zero-os nodes 
-  zeroctl verison
``` bash
./mnt/container-6/bin/zeroctl version
Version: 1.1.0-alpha
Build: 4001118 2017-09-20T07:07:04+0000
Runtime: go1.8.3 linux
```
```yaml
etcd_cluster__myetcd:
  nodes:
    - '525400123456'

storage_cluster__mycluster1:
  label: mycluster
  nrServer: 2
  diskType: hdd
  clusterType: block
  dataShards: 1
  parityShards: 1
  nodes:
   - '525400123456'
   - '000000111111'

storage_cluster__mycluster2:
  label: mycluster
  nrServer: 2
  diskType: hdd
  metadiskType: hdd
  clusterType: object
  dataShards: 1
  parityShards: 1
  nodes:
   - '000000111111'
   - '525400123456' 
```
## procedure

cmd :
```bash 
/bin/zeroctl copy vdisk --config 172.17.3.89:2379 template:ubuntu-1604 vdisk-59ca353772436032c1035070 mycluster1 --data-shards 1 --parity-shards 1
```

## Error

```bash 
failed to copy/generate tlog data for vdisk `vdisk-59ca353772436032c1035070`: [{"addrs":["172.17.3.89:2002"],"kind":"0-stor","error":{"code":14,"message":"transport is closing"},"code":400}] '
```
