### ISSUE TITLE
zeroctl copy vdisk does not complain when block sizes do not match

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-Disk#564]
## version

```
zeroctl version
Version: 1.1.0-beta-1
Build: ef49d8a 2017-10-22T13:14:48-0500
Runtime: go1.9.1 darwin
```

> (master)

## how to reproduce

config:

```yaml
storageClusters:
  a:
    servers:
      - address: localhost:16380
      - address: localhost:16381
      - address: localhost:16382
  b:
    servers:
      - address: localhost:16383
      - address: localhost:16384
      - address: localhost:16385
vdisks:
  foo:
    type: db
    blockSize: 4096
    size: 10
    nbd:
      storageClusterID: a
  bar:
    type: db
    blockSize: 16384
    size: 10
    nbd:
      storageClusterID: b
```

create `foo` vdisk:

```
$ nbdserver --address=":6666" --protocol="tcp"
# ...
$ qemu-img convert -p -n myimg.img -O nbd nbd+tcp://localhost:6666/foo
    (100.00/100%)
```

copy `foo` vdisk as `bar`

```
$ zeroctl copy vdisk foo bar b -v
```

## expected result

This is wrong however, as even though the copying went successful, the `bar` vdisk will never be able to boot up as the block sizes don't match up. Ideally the command is not executed and an error is returned instead.
