### ISSUE TITLE
zeroctl list vdisks raises an error if no vdisks are found

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-Disk#598]
I have a block storagecluster (config in etcd, and running ardbs only), when running `zeroctl list vdisks myblockcluster --config 192.168.122.76:2379` without having any vdisks created it raises an error not just return an empty list/string. I thing the default behavior should be an empty list or string not raising an error

```
Error: redigo: nil returned
Usage:
  zeroctl list vdisks (clusterID|address[@db]) [flags]

Flags:
      --config SourceConfig   config resource: dialstrings (etcd cluster) or path (yaml file) (default config.yml)
  -h, --help                  help for vdisks
      --name string           list only vdisks which match the given name (supports regexp)

Global Flags:
  -v, --verbose   log available information

redigo: nil returned
```

The config I have in my etcd is below
```yml
myblockcluster:cluster:conf:storage
===========================
servers:
- address: 192.168.122.76:2000
- address: 192.168.122.79:2000
```
